### ISSUE TITLE
Feature request: import from anki

### ISSUE THREAD

**Issue by cocoonkid** [reuseman/flashcards-obsidian#8]
**Describe the solution you'd like**
Add a function to sync/import already existing anki cards into obsidian,

**Describe alternatives you've considered**
Doing it manually but they are a lot ;-)

**Comment by reuseman** [comment]
It makes sense, and I understand your point, but honestly it's not in my top priorities. The reason is that I want to refine and improve the sync from Obsidian to Anki that seems to be more valuable. Of course, it would be a nice to have even the opposite way, but it requires quite a lot of work and these days I do not have so much time. So I really need to prioritize. Moreover, based on what criteria cards from Anki should be created as notes? Based on decks, on a group of tags that the user can manually define? It does not seem straightforward how to implement it in a way that is really useful and does not require the user to edit what the plugin generates from Anki.

**Comment by reuseman** [comment]
This feature will not be implemented by this plugin. By design, the idea is to consider Obsidian as the source of truth.
